keys:
  - &identity age16wgljvvhjsyu5xhstzy0gr258m7fk9vrqhe9yxy4y4jc08g2nsuqqep6lt
  - &host_autherror age1ghc5ldh2pfn5ss9sd7twhh38avwl7vtlxlwqjawh62ukl7syl5gs8lnl34

creation_rules:
  - path_regex: host_autherror.yaml$
    key_groups:
      - age:
        - *identity
        - *host_autherror
  - path_regex: user_error.yaml$
    key_groups:
      - age:
          - *identity
