keys:
  - &users:
    - &master age1w7zdmmk6ahvhndlv80yagamt8zlus73mcfu4h7d0w5fsu9k0wpnsy7qf4h
  - &hosts:
    - &autherror age1g6035stvj3s2pc5xf86crm950ytdh7krpeas78czjj7pc85p6u0q7tst9l
    - &authmac age18dgtuphzpue58m4y32962stul02d8pz47kqkazkyl363v6dt4q3q87ed7a
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *master
        - *autherror
        - *authmac
