keys:
  - &users:
    - &master age1w7zdmmk6ahvhndlv80yagamt8zlus73mcfu4h7d0w5fsu9k0wpnsy7qf4h
  - &hosts:
    - &autherror age1g6035stvj3s2pc5xf86crm950ytdh7krpeas78czjj7pc85p6u0q7tst9l
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *master
        - *autherror
