keys:
  - &identity age16wgljvvhjsyu5xhstzy0gr258m7fk9vrqhe9yxy4y4jc08g2nsuqqep6lt
  - &host_autherror age15as90tf34g2nvhc0j0hgty30mz0kl99mmhd4hfmvqzgvm36n6ykqf68u6x

creation_rules:
  - path_regex: host_autherror.yaml$
    key_groups:
      - age:
        - *identity
        - *host_autherror
  - path_regex: user_error.yaml$
    key_groups:
      - age:
          - *identity
